#!/bin/bash
NAME="Jellyfin"
URL="http://192.168.0.226:8096/web/"

if curl -fsS --max-time 5 "$URL" >/dev/null; then
  echo "OK|$NAME|Online|$URL"
  exit 0
else
  echo "DOWN|$NAME|Down|$URL"
  exit 1
fi
