#!/bin/bash
NAME="Open WebUI"

if docker ps --format '{{.Names}} {{.Status}}' | grep -q '^open-webui .*Up'; then
  STATUS=$(docker ps --format '{{.Names}} {{.Status}}' | grep '^open-webui ' | cut -d' ' -f2-)
  echo "OK|$NAME|$STATUS|docker:open-webui"
  exit 0
else
  echo "DOWN|$NAME|Down|docker:open-webui"
  exit 1
fi
